from pathlib import Path
from html import escape as e
import json
root=Path(__file__).resolve().parents[1]
dist=root/'dist'
guides=json.loads((root/'content/guides.json').read_text())
mention='En tant que Partenaire Amazon, je réalise un bénéfice sur les achats remplissant les conditions requises.'
head=(dist/'index.html').read_text().split('<head>')[1].split('</head>')[0]
head=head[:head.index('  <script')]

def page(title, description, body, sub=False):
    base='../' if sub else './'
    h=head.replace('Road Trip — L’essentiel pour prendre la route',e(title)+' | Road Trip')
    h=h.replace('Road Trip : une sélection d’équipements pour prendre la route, vivre dehors et profiter du voyage.',e(description))
    h=h.replace('./style.css',base+'style.css')
    return f'''<!doctype html><html lang="fr"><head>{h}</head><body><a class="skip-link" href="#contenu">Aller au contenu</a><header class="header wrap"><a class="brand" href="{base}">ROAD TRIP<span class="brand-dot">.</span></a><nav aria-label="Navigation principale"><a href="{base}guides.html">Les guides</a><a class="nav-button" href="{base}a-propos.html">À propos</a></nav></header><main id="contenu" class="reading wrap"><a href="{base}guides.html">← Tous les guides</a>{body}</main>{footer(base)}</body></html>'''

def footer(base='./'):
    return f'''<footer class="footer wrap site-footer"><div><a class="brand" href="{base}">ROAD TRIP.</a><p>{mention}</p></div><nav aria-label="Informations du site"><a href="{base}guides.html">Guides</a><a href="{base}a-propos.html">À propos et méthode</a><a href="{base}transparence.html">Affiliation</a><a href="{base}confidentialite.html">Confidentialité</a></nav></footer>'''

(dist/'guides').mkdir(exist_ok=True)
cards=[]
for g in guides:
    body=f'<p class="eyebrow">{e(g["category"])}</p><h1>{e(g["title"])}</h1><p class="article-meta">Rédaction Road Trip · Publié le 22 septembre 2026 · Guide pratique</p><p class="lead">{e(g["intro"])}</p>'
    for title,text in g['sections']: body+=f'<section><h2>{e(title)}</h2><p>{e(text)}</p></section>'
    body+='<aside class="editorial-note">Ce guide présente une méthode de préparation. Il ne rapporte pas un test produit ni un voyage personnel. Les notices des fabricants et les consignes locales restent les références pour votre équipement et vos activités.</aside>'
    body+='<p><a href="../a-propos.html">Notre méthode éditoriale</a> · <a href="../transparence.html">Comprendre les liens affiliés</a></p>'
    (dist/'guides'/f'{g["slug"]}.html').write_text(page(g['title'],g['intro'],body,True))
    cards.append(f'<article class="guide-card"><p class="eyebrow">{e(g["category"])}</p><h3><a href="./guides/{g["slug"]}.html">{e(g["title"])}</a></h3><p>{e(g["intro"])}</p><a class="guide-read" href="./guides/{g["slug"]}.html">Lire le guide →</a></article>')
index='<p class="eyebrow">LE CARNET PRATIQUE</p><h1>Préparer la route.</h1><p class="lead">Dix guides pour organiser le départ, comparer les équipements et garder de la place pour le voyage.</p><div class="guide-grid">'+''.join(cards)+'</div>'
(dist/'guides.html').write_text(page('Tous les guides','Guides pratiques pour organiser un road trip et choisir ses équipements.',index))
info={
'a-propos':('À propos et méthode éditoriale','''<h1>Des repères pour partir simplement.</h1><p class="lead">Road Trip est un site éditorial francophone consacré à l’organisation des escapades en voiture et aux équipements de voyage.</p><h2>Ce que vous trouverez ici</h2><p>Nos guides proposent des méthodes de préparation : partir de ses usages, vérifier les dimensions, organiser les affaires et comparer les contraintes avant un achat. Le site ne vend pas de produits et ne prend pas de réservations.</p><h2>Comment les contenus sont préparés</h2><p>Les guides de lancement ont été rédigés avec l’aide d’une intelligence artificielle. Ils présentent des conseils généraux d’organisation et ne prétendent pas restituer des essais sur le terrain. Aucun avis client, résultat de test ou expérience de voyage n’est inventé. Lorsqu’un futur article rapporte un essai personnel, il devra préciser le matériel, les conditions et les limites de cet essai.</p><h2>Nos critères de comparaison</h2><p>Nous privilégions l’usage, l’encombrement, les compatibilités documentées, les contraintes de rangement et le contenu réel de l’offre. Un lien marchand ne démontre pas qu’un produit a été testé. Les informations techniques doivent être contrôlées dans la documentation du fabricant avant l’achat.</p><h2>Signaler une erreur</h2><p>Vous pouvez signaler une erreur éditoriale dans les <a href="https://github.com/EvkohLand/Road-trip/issues">issues du projet GitHub</a> si vous disposez d’un compte. Ce canal est public : n’y déposez aucune donnée personnelle, commande ou information confidentielle.</p><h2>Crédit photographique</h2><p>Photo d’accueil : Dimitry Anikin, <a href="https://commons.wikimedia.org/wiki/File:Gro%C3%9Fglockner-Hochalpenstra%C3%9Fe_2.jpg">Großglockner-Hochalpenstraße 2</a>, Wikimedia Commons, licence CC0. Image redimensionnée.</p>'''),
'transparence':('Affiliation et transparence',f'''<h1>Des liens identifiés, un choix qui vous appartient.</h1><p class="lead">{mention}</p><h2>Reconnaître un lien rémunéré</h2><p>Les liens commerciaux rémunérés portent la mention « Publicité · lien affilié » à côté du bouton. Un achat éligible peut générer une commission pour le site, sans coût supplémentaire lié à ce lien. Vous êtes libre de consulter les guides sans acheter.</p><h2>Un site éditorial indépendant</h2><p>Road Trip n’est pas une boutique Amazon et ne représente pas Amazon. La participation au programme ne signifie pas qu’Amazon approuve nos articles. Le vendeur indiqué sur la page marchande gère la vente ; les conditions de commande, de livraison et de retour sont celles qui y sont présentées.</p><h2>Prix, disponibilité et avis</h2><p>Nous n’affichons pas de prix ni de disponibilité Amazon recopiés manuellement. Consultez la fiche marchande pour connaître l’offre au moment de votre visite. Nous ne reproduisons ni étoiles ni avis clients Amazon. Les descriptions éditoriales ne sont pas des preuves de performance.</p><h2>Lors d’un clic</h2><p>Le lien peut transmettre un identifiant d’affiliation au marchand pour attribuer les achats éligibles. La destination Amazon est indiquée avant le clic. Aucun transfert automatique vers un marchand n’est déclenché à la simple lecture du site. Consultez aussi notre <a href="./confidentialite.html">page de confidentialité</a>.</p>'''),
'confidentialite':('Confidentialité', '''<h1>Votre navigation, en clair.</h1><p class="article-meta">Version du 22 septembre 2026</p><h2>Sur Road Trip</h2><p>Cette version du site ne propose ni compte utilisateur, ni formulaire, ni newsletter, ni paiement. Le code du site n’installe aucun cookie, ne lit pas le stockage local et n’intègre aucun outil d’analyse d’audience ou pixel publicitaire. Les polices sont celles de votre appareil et les images sont servies avec le site.</p><h2>Hébergement GitHub Pages</h2><p>GitHub Pages reçoit les données techniques nécessaires à la fourniture des pages. GitHub indique notamment enregistrer l’adresse IP des visiteurs pour des raisons de sécurité, même sans connexion à un compte GitHub. Les durées et modalités de ces traitements relèvent des informations publiées par GitHub ; nous ne leur attribuons pas une durée que nous ne pouvons pas vérifier.</p><p>Consultez la <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">déclaration de confidentialité de GitHub</a> et sa <a href="https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages">documentation Pages</a> pour connaître ces traitements et les moyens d’exercer vos droits auprès de GitHub.</p><h2>Liens vers Amazon et d’autres sites</h2><p>Un clic sur un lien externe vous conduit sur un autre site. Les liens affiliés peuvent transmettre l’identifiant du partenaire et permettre à Amazon d’attribuer un achat. Amazon peut utiliser ses propres cookies et traiter des informations relatives à votre visite selon ses paramètres et sa <a href="https://www.amazon.fr/gp/help/customer/display.html?nodeId=201909010">politique de confidentialité</a>. Ces technologies ne sont pas chargées sur Road Trip par un widget Amazon.</p><h2>Liens de signalement</h2><p>Si vous ouvrez une issue GitHub, vous utilisez le service GitHub et les informations saisies peuvent devenir publiques. Ne publiez pas de données sensibles dans ce canal. Cette page décrit les fonctions actuellement présentes ; l’ajout futur d’un formulaire, d’un outil statistique ou d’un contenu intégré devra entraîner une nouvelle évaluation et une mise à jour de cette information.</p>''')}
for slug,(title,body) in info.items(): (dist/f'{slug}.html').write_text(page(title,title+' du site Road Trip.',body))
p=dist/'index.html'; s=p.read_text()
start=s.index('<footer'); end=s.index('</footer>',start)+len('</footer>'); s=s[:start]+footer()+s[end:]
if 'id="guides"' not in s:
    s=s.replace('    <section id="esprit"','    <section id="guides" class="wrap guide-section"><div class="section-heading"><div><p class="eyebrow">LE CARNET PRATIQUE</p><h2>Préparer, choisir, partir.</h2></div><a href="./guides.html">Voir les dix guides →</a></div><div class="guide-grid">'+''.join(cards[:3])+'</div></section>\n    <section id="esprit"')
s=s.replace('<a href="#esprit">L’esprit road trip</a>','<a href="./guides.html">Les guides</a>')
s=s.replace('Transparence : lorsqu’un lien est indiqué « lien affilié », un achat peut nous rapporter une commission, sans surcoût pour vous.',mention+' Les liens commerciaux sont signalés à côté des boutons.')
s=s.replace('<div id="products" class="product-grid"></div><noscript><p>Activez JavaScript pour consulter les équipements et leurs liens.</p></noscript>','<div id="products" class="product-grid">'+''.join(cards[i] for i in [3,4,1])+'</div>')
p.write_text(s)
print(f'Generated {len(guides)} guides and {len(info)+1} information/index pages.')
